---
- name: Timereport
  hosts: managed_nodes
  become: yes
  gather_facts: true  
  
  tasks:
  - name: Get Report
    uptimecheck:
    register: uptime_data
 
  - name: Create report
    vars:
     suptime: "{{ uptime_data.uptime }}" 
    template:
       src: uptime.j2
       dest: "{{ inventory_hostname }}"
    delegate_to: localhost
