---
# tasks file for roles/apache_vhost
- name: install httpd
  yum:
    name: httpd
    state: latest

- name: start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: ensure vhost directory is present
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory

- name: deliver html content
  copy:
    src: web.html
    dest: "/var/www/vhosts/{{ ansible_hostname }}/index.html"

- name: template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd

- name: Create file with content
  copy:
    dest: whoami.html
    content: |
       “I’m tomato"
  delegate_to: localhost

- name: deliver whoami content
  copy:
    src: whoami.html
    dest:  "/var/www/vhosts/{{ ansible_hostname }}/"

- name: Loop
  vars:
    list1: ['i.nice potato','ii.big potato','iii.cool potato']
  template: 
    src: loop_template.j2
    dest: whoami2.html
    mode: 0777
  delegate_to: localhost

- name: deliver whoami content
  copy:
    src: whoami2.html
    dest:  "/var/www/vhosts/{{ ansible_hostname }}/"

